name: Snake Animation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update_snake_animation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Generate Snake Animation
      run: |
        # Aquí iría el código para generar la animación de la serpiente
        git add -A
        git commit -m "Update snake animation" || exit 0
        git push
