name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Esto ejecuta el workflow automáticamente todos los días a medianoche (UTC)
  workflow_dispatch:  # Esto permite ejecutar el workflow manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: WoolyOlvel
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Commit and push if changed
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add -A
          git commit -m "Update snake animation" || exit 0
          git push
